# Generated by Django 5.2.8 on 2025-12-03 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_remove_producto_stock_remove_producto_talla_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='caracteristicas',
            field=models.TextField(blank=True, help_text='Características especiales (ej: Resistente al agua, Cierre magnético, Ajustable)', null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, help_text='Color principal del accesorio', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo_accesorio',
            field=models.CharField(blank=True, choices=[('mochila', 'Mochila'), ('cinturon', 'Cinturón'), ('cartera', 'Cartera'), ('cadena', 'Cadena'), ('gorra', 'Gorra'), ('llavero', 'Llavero'), ('billetera', 'Billetera'), ('riñonera', 'Riñonera'), ('collar', 'Collar'), ('pulsera', 'Pulsera'), ('anillo', 'Anillo'), ('bolso', 'Bolso'), ('otro', 'Otro')], help_text='Tipo específico de accesorio', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='dimensiones',
            field=models.CharField(blank=True, help_text='Dimensiones del accesorio (ej: 30x40cm, Largo ajustable 80-120cm)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='material',
            field=models.CharField(blank=True, help_text='Material del accesorio (ej: Cuero sintético, Lona, Acero inoxidable)', max_length=100, null=True),
        ),
    ]
